
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Javi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    GestorConexion ges = new GestorConexion();

    public VentanaPrincipal() {
        initComponents();
        deshabilitarBotones();
        setIconImage(new ImageIcon(getClass().getResource("/img/icons8-cd-30.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuerys = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton_Borrar_Cancion = new javax.swing.JButton();
        jButtonSelectArtista = new javax.swing.JButton();
        jTextField_Nombre_borrar_Arts = new javax.swing.JTextField();
        jButtonSelectAll = new javax.swing.JButton();
        jTextField_Nombre_borrar_Canc = new javax.swing.JTextField();
        jButtonSelectCancion = new javax.swing.JButton();
        jTextField_Nombre_borrar_Album = new javax.swing.JTextField();
        jButtonSelectAlbum = new javax.swing.JButton();
        jLabelIUPDATES = new javax.swing.JLabel();
        jButtonConectar = new javax.swing.JButton();
        jLabelmodfNombreC = new javax.swing.JLabel();
        jLabelmodfDuracionC = new javax.swing.JLabel();
        jLabelmodfAlbumC = new javax.swing.JLabel();
        jLabelmodfArtistaC = new javax.swing.JLabel();
        jComboBoxCanciones = new javax.swing.JComboBox<>();
        jTextField_Duracion_album = new javax.swing.JTextField();
        jTextField_Modf_Nombre_cancion = new javax.swing.JTextField();
        jTextField_Nombre_cancion = new javax.swing.JTextField();
        jTextField_Modf_Duracion_cancion = new javax.swing.JTextField();
        jTextField_Duracion_cancion = new javax.swing.JTextField();
        jComboBoxModfAlbumesC = new javax.swing.JComboBox<>();
        jButton_Añadir_Artista = new javax.swing.JButton();
        jComboBoxModfArtistasCancion = new javax.swing.JComboBox<>();
        jButton_Añadir_Album = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButton_Añadir_Cancion = new javax.swing.JButton();
        jButtonCrearTabla = new javax.swing.JButton();
        jComboBoxArtistasAlbum = new javax.swing.JComboBox<>();
        jButtonRellenarTabla = new javax.swing.JButton();
        jComboBoxAlbumes = new javax.swing.JComboBox<>();
        jLabelSELECTS = new javax.swing.JLabel();
        jComboBoxArtistasCancion = new javax.swing.JComboBox<>();
        jLabelDELETES = new javax.swing.JLabel();
        jLabelDesconectar = new javax.swing.JLabel();
        jLabelALTER_CREATE = new javax.swing.JLabel();
        jButtonDesconectar = new javax.swing.JButton();
        jButtonBorrarTabla = new javax.swing.JButton();
        jLabelINSERTS = new javax.swing.JLabel();
        jTextField_Nombre_artista = new javax.swing.JTextField();
        jTextField_Nombre_album = new javax.swing.JTextField();
        jTextField_Fech_publ_album = new javax.swing.JTextField();
        jTextFieldBuscar_cancion = new javax.swing.JTextField();
        jTextFieldBuscar_album = new javax.swing.JTextField();
        jButton_Borrar_Artista = new javax.swing.JButton();
        jButtonBuscarCancion = new javax.swing.JButton();
        jButton_Borrar_Album = new javax.swing.JButton();
        jButtonBuscarAlbum = new javax.swing.JButton();
        jButtonModoNoche = new javax.swing.JButton();
        jButtonModoDia = new javax.swing.JButton();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(500, 650));

        jTextAreaQuerys.setEditable(false);
        jTextAreaQuerys.setBackground(new java.awt.Color(102, 204, 255));
        jTextAreaQuerys.setColumns(20);
        jTextAreaQuerys.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaQuerys.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuerys);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Borrar_Cancion.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Borrar_Cancion.setText("BORRAR CANCIÓN");
        jButton_Borrar_Cancion.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_CancionActionPerformed(evt);
            }
        });

        jButtonSelectArtista.setBackground(new java.awt.Color(51, 204, 255));
        jButtonSelectArtista.setText("CONSULTAR ARTISTAS");
        jButtonSelectArtista.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelectArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectArtistaActionPerformed(evt);
            }
        });

        jTextField_Nombre_borrar_Arts.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_borrar_Arts.setToolTipText("Nombre del artista");

        jButtonSelectAll.setBackground(new java.awt.Color(51, 204, 255));
        jButtonSelectAll.setText("CONSULTAR TODO");
        jButtonSelectAll.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAllActionPerformed(evt);
            }
        });

        jTextField_Nombre_borrar_Canc.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_borrar_Canc.setToolTipText("Nombre de la cancion");

        jButtonSelectCancion.setBackground(new java.awt.Color(51, 204, 255));
        jButtonSelectCancion.setText("CONSULTAR CANCIONES");
        jButtonSelectCancion.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelectCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectCancionActionPerformed(evt);
            }
        });

        jTextField_Nombre_borrar_Album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_borrar_Album.setToolTipText("Nombre del album");

        jButtonSelectAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jButtonSelectAlbum.setText("CONSULTAR ALBUMES");
        jButtonSelectAlbum.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonSelectAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAlbumActionPerformed(evt);
            }
        });

        jLabelIUPDATES.setBackground(new java.awt.Color(153, 204, 255));
        jLabelIUPDATES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIUPDATES.setText("MODIFICAR  DATOS");
        jLabelIUPDATES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelIUPDATES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelIUPDATES.setOpaque(true);

        jButtonConectar.setBackground(new java.awt.Color(51, 204, 255));
        jButtonConectar.setText("Conectar/Actualizar");
        jButtonConectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jLabelmodfNombreC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfNombreC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelmodfNombreC.setText("NOMBRE: ");
        jLabelmodfNombreC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelmodfNombreC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelmodfNombreC.setOpaque(true);

        jLabelmodfDuracionC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfDuracionC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelmodfDuracionC.setText("DURACIÓN: ");
        jLabelmodfDuracionC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelmodfDuracionC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelmodfDuracionC.setOpaque(true);

        jLabelmodfAlbumC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfAlbumC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelmodfAlbumC.setText("ALBUM: ");
        jLabelmodfAlbumC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelmodfAlbumC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelmodfAlbumC.setOpaque(true);

        jLabelmodfArtistaC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfArtistaC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelmodfArtistaC.setText("ARTISTA: ");
        jLabelmodfArtistaC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelmodfArtistaC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelmodfArtistaC.setOpaque(true);

        jComboBoxCanciones.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxCanciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField_Duracion_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Duracion_album.setToolTipText("Duracion");

        jTextField_Modf_Nombre_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Modf_Nombre_cancion.setToolTipText("");

        jTextField_Nombre_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_cancion.setToolTipText("Nombre");

        jTextField_Modf_Duracion_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Modf_Duracion_cancion.setToolTipText("");

        jTextField_Duracion_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Duracion_cancion.setToolTipText("Duracion");

        jComboBoxModfAlbumesC.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxModfAlbumesC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Añadir_Artista.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Artista.setText("AÑADIR ARTISTA");
        jButton_Añadir_Artista.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_ArtistaActionPerformed(evt);
            }
        });

        jComboBoxModfArtistasCancion.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxModfArtistasCancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Añadir_Album.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Album.setText("AÑADIR ALBUM");
        jButton_Añadir_Album.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_AlbumActionPerformed(evt);
            }
        });

        jButtonModificar.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButton_Añadir_Cancion.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Cancion.setText("AÑADIR CANCIÓN");
        jButton_Añadir_Cancion.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Añadir_Cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Añadir_CancionActionPerformed(evt);
            }
        });

        jButtonCrearTabla.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCrearTabla.setText("CREAR TABLA REPRODUCCIONES");
        jButtonCrearTabla.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaActionPerformed(evt);
            }
        });

        jComboBoxArtistasAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxArtistasAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRellenarTabla.setBackground(new java.awt.Color(51, 204, 255));
        jButtonRellenarTabla.setText("RELLENAR TABLA");
        jButtonRellenarTabla.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonRellenarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRellenarTablaActionPerformed(evt);
            }
        });

        jComboBoxAlbumes.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxAlbumes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSELECTS.setBackground(new java.awt.Color(153, 204, 255));
        jLabelSELECTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSELECTS.setText("CONSULTAR  DATOS");
        jLabelSELECTS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelSELECTS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSELECTS.setOpaque(true);

        jComboBoxArtistasCancion.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxArtistasCancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDELETES.setBackground(new java.awt.Color(153, 204, 255));
        jLabelDELETES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDELETES.setText("BORRAR  DATOS");
        jLabelDELETES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelDELETES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDELETES.setOpaque(true);

        jLabelDesconectar.setBackground(new java.awt.Color(153, 204, 255));
        jLabelDesconectar.setText("MANEJAR CONEXIÓN CON LA BBDD");
        jLabelDesconectar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelDesconectar.setOpaque(true);

        jLabelALTER_CREATE.setBackground(new java.awt.Color(153, 204, 255));
        jLabelALTER_CREATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelALTER_CREATE.setText("EDITAR BASE DE DATOS");
        jLabelALTER_CREATE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelALTER_CREATE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelALTER_CREATE.setOpaque(true);

        jButtonDesconectar.setBackground(new java.awt.Color(51, 204, 255));
        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        jButtonBorrarTabla.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBorrarTabla.setText("BORRAR TABLA");
        jButtonBorrarTabla.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonBorrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTablaActionPerformed(evt);
            }
        });

        jLabelINSERTS.setBackground(new java.awt.Color(153, 204, 255));
        jLabelINSERTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelINSERTS.setText("INSERTAR  DATOS");
        jLabelINSERTS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelINSERTS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelINSERTS.setOpaque(true);

        jTextField_Nombre_artista.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_artista.setToolTipText("Nombre");

        jTextField_Nombre_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_album.setToolTipText("Nombre");

        jTextField_Fech_publ_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Fech_publ_album.setToolTipText("Fecha_Publicacion");

        jTextFieldBuscar_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextFieldBuscar_cancion.setToolTipText("Nombre de la Cancion");

        jTextFieldBuscar_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextFieldBuscar_album.setToolTipText("Nombre del album");

        jButton_Borrar_Artista.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Borrar_Artista.setText("BORAR ARTISTA");
        jButton_Borrar_Artista.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_ArtistaActionPerformed(evt);
            }
        });

        jButtonBuscarCancion.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBuscarCancion.setText("BUSCAR CANCIÓN");
        jButtonBuscarCancion.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCancionActionPerformed(evt);
            }
        });

        jButton_Borrar_Album.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Borrar_Album.setText("BORRAR ALBUM");
        jButton_Borrar_Album.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Borrar_Album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Borrar_AlbumActionPerformed(evt);
            }
        });

        jButtonBuscarAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBuscarAlbum.setText("BUSCAR ALBUM");
        jButtonBuscarAlbum.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonBuscarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlbumActionPerformed(evt);
            }
        });

        jButtonModoNoche.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModoNoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-luna-brillante-32 (2).png"))); // NOI18N
        jButtonModoNoche.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModoNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoNocheActionPerformed(evt);
            }
        });

        jButtonModoDia.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salida-del-sol-32.png"))); // NOI18N
        jButtonModoDia.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelmodfArtistaC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelmodfAlbumC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelmodfDuracionC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelmodfNombreC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCanciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Modf_Duracion_cancion)
                            .addComponent(jTextField_Modf_Nombre_cancion)
                            .addComponent(jComboBoxModfAlbumesC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxModfArtistasCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelINSERTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelALTER_CREATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Añadir_Artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Nombre_artista))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Nombre_album)
                            .addComponent(jTextField_Fech_publ_album)
                            .addComponent(jTextField_Duracion_album)
                            .addComponent(jButton_Añadir_Album, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxArtistasAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_Nombre_cancion)
                            .addComponent(jTextField_Duracion_cancion)
                            .addComponent(jButton_Añadir_Cancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxAlbumes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxArtistasCancion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelDELETES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Nombre_borrar_Arts, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Borrar_Artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Borrar_Album, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Nombre_borrar_Album))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Nombre_borrar_Canc)
                            .addComponent(jButton_Borrar_Cancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelIUPDATES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSELECTS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBuscarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBuscar_cancion)
                            .addComponent(jTextFieldBuscar_album, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSelectArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelectAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSelectCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRellenarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModoNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonModoNoche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModoDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelALTER_CREATE, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRellenarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabelINSERTS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Añadir_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Añadir_Album, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Añadir_Cancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Nombre_album, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Fech_publ_album, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Duracion_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Duracion_album, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxArtistasAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxArtistasCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelIUPDATES, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelmodfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelmodfDuracionC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_Modf_Nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Modf_Duracion_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxModfAlbumesC)
                    .addComponent(jLabelmodfAlbumC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmodfArtistaC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModfArtistasCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelDELETES, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_Borrar_Artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Borrar_Album, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Borrar_Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Nombre_borrar_Album)
                    .addComponent(jTextField_Nombre_borrar_Canc)
                    .addComponent(jTextField_Nombre_borrar_Arts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabelSELECTS, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSelectAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBuscar_cancion)
                            .addComponent(jButtonSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldBuscar_album, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBuscarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSelectArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonBuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTextField_Nombre_artista.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        ges.cerrar_conexion();
        deshabilitarBotones();
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    private void jButtonBorrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTablaActionPerformed
        ges.dropTable();
        jButtonCrearTabla.setEnabled(true);
        jButtonBorrarTabla.setEnabled(false);
    }//GEN-LAST:event_jButtonBorrarTablaActionPerformed

    private void jButton_Añadir_ArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_ArtistaActionPerformed
        ges.insertarArtista(jTextField_Nombre_artista.getText());
        jTextField_Nombre_artista.setText("");
    }//GEN-LAST:event_jButton_Añadir_ArtistaActionPerformed

    private void jButton_Añadir_AlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_AlbumActionPerformed
        ges.insertarAlbum(jTextField_Nombre_album.getText(), jTextField_Fech_publ_album.getText(), jTextField_Duracion_album.getText(),
                jComboBoxArtistasAlbum.getSelectedIndex() + 1);
        jTextField_Nombre_album.setText("");
        jTextField_Fech_publ_album.setText("");
        jTextField_Duracion_album.setText("");
    }//GEN-LAST:event_jButton_Añadir_AlbumActionPerformed

    private void jButton_Añadir_CancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Añadir_CancionActionPerformed
        ges.insertarCancion(jTextField_Nombre_cancion.getText(), jTextField_Duracion_cancion.getText(), jComboBoxAlbumes.getSelectedIndex() + 1,
                jComboBoxArtistasCancion.getSelectedIndex() + 1);
        jTextField_Nombre_cancion.setText("");
        jTextField_Duracion_cancion.setText("");
    }//GEN-LAST:event_jButton_Añadir_CancionActionPerformed

    private void jButton_Borrar_ArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_ArtistaActionPerformed
        ges.borrar(jTextField_Nombre_borrar_Arts.getText(), 0);
        jTextField_Nombre_borrar_Arts.setText("");
    }//GEN-LAST:event_jButton_Borrar_ArtistaActionPerformed

    private void jButton_Borrar_AlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_AlbumActionPerformed
        ges.borrar(jTextField_Nombre_borrar_Album.getText(), 1);
        jTextField_Nombre_borrar_Album.setText("");
    }//GEN-LAST:event_jButton_Borrar_AlbumActionPerformed

    private void jButton_Borrar_CancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Borrar_CancionActionPerformed
        ges.borrar(jTextField_Nombre_borrar_Canc.getText(), 2);
        jTextField_Nombre_borrar_Canc.setText("");
    }//GEN-LAST:event_jButton_Borrar_CancionActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        ges.modificar(jTextField_Modf_Nombre_cancion.getText(), jTextField_Modf_Duracion_cancion.getText(),
                jComboBoxModfAlbumesC.getSelectedIndex() + 1, jComboBoxModfArtistasCancion.getSelectedIndex() + 1, jComboBoxCanciones.getSelectedIndex() + 1);
        jTextField_Modf_Nombre_cancion.setText("");
        jTextField_Modf_Duracion_cancion.setText("");
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaActionPerformed
        ges.createTable();
        jButtonCrearTabla.setEnabled(false);
        jButtonBorrarTabla.setEnabled(true);
        jButtonRellenarTabla.setEnabled(true);
    }//GEN-LAST:event_jButtonCrearTablaActionPerformed

    private void jButtonRellenarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRellenarTablaActionPerformed
        ges.fillTable();
        jButtonRellenarTabla.setEnabled(false);
    }//GEN-LAST:event_jButtonRellenarTablaActionPerformed

    private void jButtonBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCancionActionPerformed
        jTextAreaQuerys.setText(ges.buscarCancion(jTextFieldBuscar_cancion.getText()));
        jDialog1.setVisible(true);
        jTextFieldBuscar_cancion.setText("");
    }//GEN-LAST:event_jButtonBuscarCancionActionPerformed

    private void jButtonBuscarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlbumActionPerformed
        jTextAreaQuerys.setText(ges.buscarAlbum(jTextFieldBuscar_album.getText()));
        jDialog1.setVisible(true);
        jTextFieldBuscar_album.setText("");
    }//GEN-LAST:event_jButtonBuscarAlbumActionPerformed

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        jTextAreaQuerys.setText(ges.selectAll());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelectAllActionPerformed

    private void jButtonSelectArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectArtistaActionPerformed
        jTextAreaQuerys.setText(ges.selectArtistas());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelectArtistaActionPerformed

    private void jButtonSelectAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAlbumActionPerformed
        jTextAreaQuerys.setText(ges.selectAlbumes());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelectAlbumActionPerformed

    private void jButtonSelectCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectCancionActionPerformed
        jTextAreaQuerys.setText(ges.selectCanciones());
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonSelectCancionActionPerformed

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        if (ges.GestorConexion() == 0) {
            System.out.println("Conectado a discográfica");
            rellenarBoxAlbumes();
            rellenarBoxArtistas();
            rellenarBoxCanciones();
            conectar();
        } else if (ges.GestorConexion() == 1) {
            System.out.println("No fue posible conectarse a la bbdd");
        } else {
            System.out.println("Error en la conexion a discográfica");
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonModoNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoNocheActionPerformed
        modoNoche();
    }//GEN-LAST:event_jButtonModoNocheActionPerformed

    private void jButtonModoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoDiaActionPerformed
        modoDia();
    }//GEN-LAST:event_jButtonModoDiaActionPerformed

    private void rellenarBoxArtistas() {
        jComboBoxArtistasAlbum.removeAllItems();
        jComboBoxArtistasCancion.removeAllItems();
        jComboBoxModfArtistasCancion.removeAllItems();
        ArrayList<String> listaArtistas = new ArrayList<String>();//para la foreign key de album en canciones
        listaArtistas = ges.comboBoxArtista();
        for (int i = 0; i < listaArtistas.size(); i++) {
            jComboBoxArtistasAlbum.addItem(listaArtistas.get(i));
            jComboBoxArtistasCancion.addItem(listaArtistas.get(i));
            jComboBoxModfArtistasCancion.addItem(listaArtistas.get(i));
        }
    }

    private void rellenarBoxAlbumes() {
        jComboBoxAlbumes.removeAllItems();
        jComboBoxModfAlbumesC.removeAllItems();
        ArrayList<String> listaAlbumes = new ArrayList<String>();//para la foreign key de album en canciones
        listaAlbumes = ges.comboBoxAlbumes();
        for (int i = 0; i < listaAlbumes.size(); i++) {
            jComboBoxAlbumes.addItem(listaAlbumes.get(i));
            jComboBoxModfAlbumesC.addItem(listaAlbumes.get(i));
        }
    }

    private void rellenarBoxCanciones() {
        jComboBoxCanciones.removeAllItems();
        ArrayList<String> listaCanciones = new ArrayList<String>();//para la foreign key de album en canciones
        listaCanciones = ges.comboBoxCanciones();
        for (int i = 0; i < listaCanciones.size(); i++) {
            jComboBoxCanciones.addItem(listaCanciones.get(i));
        }
    }

    private void deshabilitarBotones() {
        jButtonDesconectar.setEnabled(false);
        jButtonCrearTabla.setEnabled(false);
        jButtonRellenarTabla.setEnabled(false);
        jButtonBorrarTabla.setEnabled(false);
        jButton_Añadir_Artista.setEnabled(false);
        jButton_Añadir_Album.setEnabled(false);
        jButton_Añadir_Cancion.setEnabled(false);
        jButtonModificar.setEnabled(false);
        jButton_Borrar_Artista.setEnabled(false);
        jButton_Borrar_Album.setEnabled(false);
        jButton_Borrar_Cancion.setEnabled(false);
        jButtonBuscarCancion.setEnabled(false);
        jButtonBuscarAlbum.setEnabled(false);
        jButtonSelectAll.setEnabled(false);
        jButtonSelectAlbum.setEnabled(false);
        jButtonSelectArtista.setEnabled(false);
        jButtonSelectCancion.setEnabled(false);

        jComboBoxArtistasAlbum.removeAllItems();
        jComboBoxArtistasCancion.removeAllItems();
        jComboBoxModfArtistasCancion.removeAllItems();
        jComboBoxAlbumes.removeAllItems();
        jComboBoxModfAlbumesC.removeAllItems();
        jComboBoxCanciones.removeAllItems();

    }

    private void conectar() {
        jButtonCrearTabla.setEnabled(true);
        jButton_Añadir_Artista.setEnabled(true);
        jButton_Añadir_Album.setEnabled(true);
        jButton_Añadir_Cancion.setEnabled(true);
        jButtonModificar.setEnabled(true);
        jButton_Borrar_Artista.setEnabled(true);
        jButton_Borrar_Album.setEnabled(true);
        jButton_Borrar_Cancion.setEnabled(true);
        jButtonBuscarCancion.setEnabled(true);
        jButtonBuscarAlbum.setEnabled(true);
        jButtonSelectAll.setEnabled(true);
        jButtonSelectAlbum.setEnabled(true);
        jButtonSelectArtista.setEnabled(true);
        jButtonSelectCancion.setEnabled(true);
        jButtonDesconectar.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTabla;
    private javax.swing.JButton jButtonBuscarAlbum;
    private javax.swing.JButton jButtonBuscarCancion;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonCrearTabla;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModoDia;
    private javax.swing.JButton jButtonModoNoche;
    private javax.swing.JButton jButtonRellenarTabla;
    private javax.swing.JButton jButtonSelectAlbum;
    private javax.swing.JButton jButtonSelectAll;
    private javax.swing.JButton jButtonSelectArtista;
    private javax.swing.JButton jButtonSelectCancion;
    private javax.swing.JButton jButton_Añadir_Album;
    private javax.swing.JButton jButton_Añadir_Artista;
    private javax.swing.JButton jButton_Añadir_Cancion;
    private javax.swing.JButton jButton_Borrar_Album;
    private javax.swing.JButton jButton_Borrar_Artista;
    private javax.swing.JButton jButton_Borrar_Cancion;
    private javax.swing.JComboBox<String> jComboBoxAlbumes;
    private javax.swing.JComboBox<String> jComboBoxArtistasAlbum;
    private javax.swing.JComboBox<String> jComboBoxArtistasCancion;
    private javax.swing.JComboBox<String> jComboBoxCanciones;
    private javax.swing.JComboBox<String> jComboBoxModfAlbumesC;
    private javax.swing.JComboBox<String> jComboBoxModfArtistasCancion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelALTER_CREATE;
    private javax.swing.JLabel jLabelDELETES;
    private javax.swing.JLabel jLabelDesconectar;
    private javax.swing.JLabel jLabelINSERTS;
    private javax.swing.JLabel jLabelIUPDATES;
    private javax.swing.JLabel jLabelSELECTS;
    private javax.swing.JLabel jLabelmodfAlbumC;
    private javax.swing.JLabel jLabelmodfArtistaC;
    private javax.swing.JLabel jLabelmodfDuracionC;
    private javax.swing.JLabel jLabelmodfNombreC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuerys;
    private javax.swing.JTextField jTextFieldBuscar_album;
    private javax.swing.JTextField jTextFieldBuscar_cancion;
    private javax.swing.JTextField jTextField_Duracion_album;
    private javax.swing.JTextField jTextField_Duracion_cancion;
    private javax.swing.JTextField jTextField_Fech_publ_album;
    private javax.swing.JTextField jTextField_Modf_Duracion_cancion;
    private javax.swing.JTextField jTextField_Modf_Nombre_cancion;
    private javax.swing.JTextField jTextField_Nombre_album;
    private javax.swing.JTextField jTextField_Nombre_artista;
    private javax.swing.JTextField jTextField_Nombre_borrar_Album;
    private javax.swing.JTextField jTextField_Nombre_borrar_Arts;
    private javax.swing.JTextField jTextField_Nombre_borrar_Canc;
    private javax.swing.JTextField jTextField_Nombre_cancion;
    // End of variables declaration//GEN-END:variables

    public void modoNoche() {
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jButton_Borrar_Cancion.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSelectArtista.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre_borrar_Arts.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSelectAll.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre_borrar_Canc.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSelectCancion.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre_borrar_Album.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSelectAlbum.setBackground(new java.awt.Color(0, 102, 102));
        jLabelIUPDATES.setBackground(new java.awt.Color(0, 102, 102));
        jButtonConectar.setBackground(new java.awt.Color(0, 102, 102));
        jLabelmodfNombreC.setBackground(new java.awt.Color(0, 102, 102));
        jLabelmodfDuracionC.setBackground(new java.awt.Color(0, 102, 102));
        jLabelmodfAlbumC.setBackground(new java.awt.Color(0, 102, 102));
        jLabelmodfArtistaC.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxCanciones.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Duracion_album.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Modf_Nombre_cancion.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Nombre_cancion.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Modf_Duracion_cancion.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Duracion_cancion.setBackground(new java.awt.Color(0, 153, 153));
        jComboBoxModfAlbumesC.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Añadir_Artista.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxModfArtistasCancion.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Añadir_Album.setBackground(new java.awt.Color(0, 102, 102));
        jButtonModificar.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Añadir_Cancion.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCrearTabla.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxArtistasAlbum.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRellenarTabla.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxAlbumes.setBackground(new java.awt.Color(0, 102, 102));
        jLabelSELECTS.setBackground(new java.awt.Color(0, 102, 102));
        jComboBoxArtistasCancion.setBackground(new java.awt.Color(0, 102, 102));
        jLabelDELETES.setBackground(new java.awt.Color(0, 102, 102));
        jLabelDesconectar.setBackground(new java.awt.Color(0, 102, 102));
        jLabelALTER_CREATE.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDesconectar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBorrarTabla.setBackground(new java.awt.Color(0, 102, 102));
        jLabelINSERTS.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre_artista.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Nombre_album.setBackground(new java.awt.Color(0, 153, 153));
        jTextField_Fech_publ_album.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldBuscar_cancion.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldBuscar_album.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Borrar_Artista.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBuscarCancion.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Borrar_Album.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBuscarAlbum.setBackground(new java.awt.Color(0, 102, 102));
        jButtonModoNoche.setBackground(new java.awt.Color(0, 102, 102));
        jButtonModoDia.setBackground(new java.awt.Color(0, 102, 102));
        jTextAreaQuerys.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Cancion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectArtista.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_borrar_Arts.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectAll.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_borrar_Canc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectCancion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_borrar_Album.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelectAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIUPDATES.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConectar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodfNombreC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodfDuracionC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodfAlbumC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmodfArtistaC.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxCanciones.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Duracion_album.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Nombre_cancion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_cancion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modf_Duracion_cancion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Duracion_cancion.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxModfAlbumesC.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Artista.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxModfArtistasCancion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Album.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Añadir_Cancion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearTabla.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxArtistasAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRellenarTabla.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxAlbumes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSELECTS.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxArtistasCancion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDELETES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelALTER_CREATE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBorrarTabla.setForeground(new java.awt.Color(255, 255, 255));
        jLabelINSERTS.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_artista.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre_album.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Fech_publ_album.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBuscar_cancion.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldBuscar_album.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Artista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarCancion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Borrar_Album.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModoNoche.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModoDia.setForeground(new java.awt.Color(255, 255, 255));
    }

    public void modoDia() {
        jTextAreaQuerys.setBackground(new java.awt.Color(102, 204, 255));
        setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jButton_Borrar_Cancion.setBackground(new java.awt.Color(51, 204, 255));
        jButtonSelectArtista.setBackground(new java.awt.Color(51, 204, 255));
        jTextField_Nombre_borrar_Arts.setBackground(new java.awt.Color(102, 204, 255));
        jButtonSelectAll.setBackground(new java.awt.Color(51, 204, 255));
        jTextField_Nombre_borrar_Canc.setBackground(new java.awt.Color(102, 204, 255));
        jButtonSelectCancion.setBackground(new java.awt.Color(51, 204, 255));
        jTextField_Nombre_borrar_Album.setBackground(new java.awt.Color(102, 204, 255));
        jButtonSelectAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jLabelIUPDATES.setBackground(new java.awt.Color(153, 204, 255));
        jButtonConectar.setBackground(new java.awt.Color(51, 204, 255));
        jLabelmodfNombreC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfDuracionC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfAlbumC.setBackground(new java.awt.Color(153, 204, 255));
        jLabelmodfArtistaC.setBackground(new java.awt.Color(153, 204, 255));
        jComboBoxCanciones.setBackground(new java.awt.Color(51, 204, 255));
        jTextField_Duracion_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Modf_Nombre_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Modf_Duracion_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Duracion_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jComboBoxModfAlbumesC.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Artista.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxModfArtistasCancion.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Album.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModificar.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Añadir_Cancion.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCrearTabla.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxArtistasAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jButtonRellenarTabla.setBackground(new java.awt.Color(51, 204, 255));
        jComboBoxAlbumes.setBackground(new java.awt.Color(51, 204, 255));
        jLabelSELECTS.setBackground(new java.awt.Color(153, 204, 255));
        jComboBoxArtistasCancion.setBackground(new java.awt.Color(51, 204, 255));
        jLabelDELETES.setBackground(new java.awt.Color(153, 204, 255));
        jLabelDesconectar.setBackground(new java.awt.Color(153, 204, 255));
        jLabelALTER_CREATE.setBackground(new java.awt.Color(153, 204, 255));
        jButtonDesconectar.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBorrarTabla.setBackground(new java.awt.Color(51, 204, 255));
        jLabelINSERTS.setBackground(new java.awt.Color(153, 204, 255));
        jTextField_Nombre_artista.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Nombre_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextField_Fech_publ_album.setBackground(new java.awt.Color(102, 204, 255));
        jTextFieldBuscar_cancion.setBackground(new java.awt.Color(102, 204, 255));
        jTextFieldBuscar_album.setBackground(new java.awt.Color(102, 204, 255));
        jButton_Borrar_Artista.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBuscarCancion.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Borrar_Album.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBuscarAlbum.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModoNoche.setBackground(new java.awt.Color(51, 204, 255));
        jButtonModoDia.setBackground(new java.awt.Color(51, 204, 255));
        jTextAreaQuerys.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Cancion.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelectArtista.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_borrar_Arts.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelectAll.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_borrar_Canc.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelectCancion.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_borrar_Album.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSelectAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIUPDATES.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConectar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmodfNombreC.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmodfDuracionC.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmodfAlbumC.setForeground(new java.awt.Color(0, 0, 0));
        jLabelmodfArtistaC.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCanciones.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Duracion_album.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Nombre_cancion.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_cancion.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Modf_Duracion_cancion.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Duracion_cancion.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxModfAlbumesC.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Artista.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxModfArtistasCancion.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Album.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Añadir_Cancion.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCrearTabla.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxArtistasAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRellenarTabla.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxAlbumes.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSELECTS.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxArtistasCancion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDELETES.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDesconectar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelALTER_CREATE.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDesconectar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrarTabla.setForeground(new java.awt.Color(0, 0, 0));
        jLabelINSERTS.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_artista.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nombre_album.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Fech_publ_album.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscar_cancion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscar_album.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Artista.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscarCancion.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Borrar_Album.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscarAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModoNoche.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModoDia.setForeground(new java.awt.Color(0, 0, 0));
    }

}
